export const CATEGORIES = [
  { id: 'all', label: 'Barchasi', emoji: '🍽️' },
  { id: 'milliy', label: 'Milliy', emoji: '🍲' },
  { id: 'burger', label: 'Burger', emoji: '🍔' },
  { id: 'pizza', label: 'Pizza', emoji: '🍕' },
  { id: 'sushi', label: 'Sushi', emoji: '🍣' },
  { id: 'grill', label: 'Grill', emoji: '🔥' },
  { id: 'fastfood', label: 'Fast Food', emoji: '🌮' },
]

export const RESTAURANTS = [
  {
    id: 1,
    name: "Toshkent Oshi",
    category: "milliy",
    image: "🍲",
    color: "#FFF3E0",
    rating: 4.9,
    reviewCount: 312,
    deliveryTime: "25-35",
    deliveryFee: 8000,
    minOrder: 30000,
    isOpen: true,
    tags: ["O'zbek taomlari", "Osh", "Somsa"],
    address: "Chilonzor tumani, 12-kvartal",
  },
  {
    id: 2,
    name: "Burger House",
    category: "burger",
    image: "🍔",
    color: "#FFF8E1",
    rating: 4.7,
    reviewCount: 189,
    deliveryTime: "20-30",
    deliveryFee: 10000,
    minOrder: 25000,
    isOpen: true,
    tags: ["Burger", "Kartoshka", "Ichimlik"],
    address: "Yunusobod tumani, 19-kvartal",
  },
  {
    id: 3,
    name: "Pizza Corner",
    category: "pizza",
    image: "🍕",
    color: "#FCE4EC",
    rating: 4.8,
    reviewCount: 245,
    deliveryTime: "30-45",
    deliveryFee: 12000,
    minOrder: 35000,
    isOpen: true,
    tags: ["Pizza", "Pasta", "Dostavka"],
    address: "Mirzo Ulug'bek tumani, 5-kvartal",
  },
  {
    id: 4,
    name: "Navbahor Milliy",
    category: "milliy",
    image: "🥘",
    color: "#E8F5E9",
    rating: 4.6,
    reviewCount: 421,
    deliveryTime: "35-50",
    deliveryFee: 6000,
    minOrder: 40000,
    isOpen: true,
    tags: ["Lag'mon", "Manti", "Shurva"],
    address: "Shayxontohur tumani, Bozor ko'chasi",
  },
  {
    id: 5,
    name: "Sushi Garden",
    category: "sushi",
    image: "🍣",
    color: "#E8EAF6",
    rating: 4.5,
    reviewCount: 98,
    deliveryTime: "40-55",
    deliveryFee: 15000,
    minOrder: 50000,
    isOpen: false,
    tags: ["Sushi", "Rolls", "Miso"],
    address: "Yakkasaroy tumani, Amir Temur ko'chasi",
  },
  {
    id: 6,
    name: "Shashlik King",
    category: "grill",
    image: "🔥",
    color: "#FBE9E7",
    rating: 4.8,
    reviewCount: 534,
    deliveryTime: "30-40",
    deliveryFee: 9000,
    minOrder: 45000,
    isOpen: true,
    tags: ["Shashlik", "Qovurma", "Grill"],
    address: "Sergeli tumani, 14-kvartal",
  },
  {
    id: 7,
    name: "KFC Toshkent",
    category: "fastfood",
    image: "🍗",
    color: "#FFFDE7",
    rating: 4.4,
    reviewCount: 667,
    deliveryTime: "15-25",
    deliveryFee: 11000,
    minOrder: 20000,
    isOpen: true,
    tags: ["Tovuq", "Burger", "Tez taom"],
    address: "Olmazor tumani, Metro yonida",
  },
  {
    id: 8,
    name: "Samarkand Plov",
    category: "milliy",
    image: "🫕",
    color: "#F3E5F5",
    rating: 4.9,
    reviewCount: 789,
    deliveryTime: "20-30",
    deliveryFee: 7000,
    minOrder: 35000,
    isOpen: true,
    tags: ["Samarqand oshi", "Dimlama", "Non"],
    address: "Uchtepa tumani, Bozor ko'chasi 45",
  }
]

export const MENU_ITEMS = {
  1: [
    { id: 101, name: "Toshkent oshi (1 kg)", price: 45000, emoji: "🍲", category: "Asosiy", popular: true, time: "35 daq", desc: "An'anaviy palov: go'sht, sabzi, piyoz bilan" },
    { id: 102, name: "Somsa (2 ta)", price: 18000, emoji: "🥟", category: "Snack", popular: true, time: "15 daq", desc: "Tandirda pishirilgan go'shtli somsa" },
    { id: 103, name: "Shurva", price: 35000, emoji: "🍜", category: "Sho'rva", popular: false, time: "20 daq", desc: "Qo'y go'shti bilan qaynatilgan shurva" },
    { id: 104, name: "Kabob (6 ta)", price: 55000, emoji: "🍖", category: "Grill", popular: true, time: "25 daq", desc: "Tandirda pishirilgan go'sht kabob" },
    { id: 105, name: "Non (1 ta)", price: 8000, emoji: "🫓", category: "Non", popular: false, time: "10 daq", desc: "Yangi pishirilgan tandirda non" },
    { id: 106, name: "Ayron (500 ml)", price: 12000, emoji: "🥛", category: "Ichimlik", popular: false, time: "5 daq", desc: "Tabiiy qatiq asosida ayron" },
  ],
  2: [
    { id: 201, name: "Classic Burger", price: 38000, emoji: "🍔", category: "Burger", popular: true, time: "20 daq", desc: "Mol go'shti, salat, pomidor, sous" },
    { id: 202, name: "BBQ Burger", price: 45000, emoji: "🍔", category: "Burger", popular: true, time: "20 daq", desc: "BBQ sous, bacon, pishloq bilan" },
    { id: 203, name: "Chicken Burger", price: 36000, emoji: "🍗", category: "Burger", popular: false, time: "20 daq", desc: "Qovurilgan tovuq, sabzavot bilan" },
    { id: 204, name: "Katta kartoshka", price: 22000, emoji: "🍟", category: "Qo'shimcha", popular: true, time: "12 daq", desc: "Oltin qovurilgan katta kartoshka" },
    { id: 205, name: "Kola (0.5L)", price: 10000, emoji: "🥤", category: "Ichimlik", popular: false, time: "3 daq", desc: "Sovutilgan Coca-Cola" },
    { id: 206, name: "Burger Seti", price: 65000, emoji: "🎁", category: "Set", popular: true, time: "22 daq", desc: "Classic Burger + kartoshka + kola" },
  ],
  3: [
    { id: 301, name: "Margarita (32sm)", price: 55000, emoji: "🍕", category: "Pizza", popular: true, time: "35 daq", desc: "Pomidor sousi, mocarella, bazilika" },
    { id: 302, name: "4 Pishloq (32sm)", price: 70000, emoji: "🍕", category: "Pizza", popular: true, time: "35 daq", desc: "To'rt xil pishloq: mocarella, cheddar, gorgonzola, parmezan" },
    { id: 303, name: "Pepperoni (32sm)", price: 68000, emoji: "🍕", category: "Pizza", popular: true, time: "35 daq", desc: "Pepperoni kolbasa, mocarella, oregano" },
    { id: 304, name: "Spaghetti Bolognese", price: 52000, emoji: "🍝", category: "Pasta", popular: false, time: "25 daq", desc: "Italyan pasta, mol go'sht sousi bilan" },
    { id: 305, name: "Tiramisu", price: 28000, emoji: "🍰", category: "Shirinlik", popular: false, time: "10 daq", desc: "Klassik italyan deserti" },
    { id: 306, name: "Lemonad", price: 15000, emoji: "🍋", category: "Ichimlik", popular: false, time: "5 daq", desc: "Limon va na'matak limonadi" },
  ],
  4: [
    { id: 401, name: "Lag'mon", price: 40000, emoji: "🍜", category: "Asosiy", popular: true, time: "30 daq", desc: "Qo'lda cho'zilgan lag'mon, go'sht, sabzavot" },
    { id: 402, name: "Manti (6 ta)", price: 35000, emoji: "🥟", category: "Asosiy", popular: true, time: "40 daq", desc: "Qo'y go'shtli an'anaviy manti" },
    { id: 403, name: "Dimlama", price: 48000, emoji: "🥘", category: "Asosiy", popular: false, time: "45 daq", desc: "Sabzavot va go'sht bilan dumlab pishirilgan" },
    { id: 404, name: "Sho'rva", price: 32000, emoji: "🍵", category: "Sho'rva", popular: false, time: "20 daq", desc: "Mol go'shti bilan shaffof sho'rva" },
    { id: 405, name: "Chuchvara", price: 30000, emoji: "🥟", category: "Asosiy", popular: true, time: "35 daq", desc: "Qo'lda qiyilgan go'shtli chuchvara" },
  ],
  5: [
    { id: 501, name: "Philadelphia Roll (8 ta)", price: 85000, emoji: "🍣", category: "Rolls", popular: true, time: "40 daq", desc: "Losos, krem pishloq, avokado" },
    { id: 502, name: "Dragon Roll (8 ta)", price: 90000, emoji: "🍣", category: "Rolls", popular: true, time: "45 daq", desc: "Krevetka tempura, avokado, losos" },
    { id: 503, name: "Miso Sho'rva", price: 25000, emoji: "🍵", category: "Sho'rva", popular: false, time: "10 daq", desc: "An'anaviy yapon miso sho'rvasi" },
    { id: 504, name: "Salmon Nigiri (2 ta)", price: 45000, emoji: "🍱", category: "Nigiri", popular: false, time: "30 daq", desc: "Yangi losos, guruch, wasabi" },
  ],
  6: [
    { id: 601, name: "Qo'y shashlik (6 ta)", price: 75000, emoji: "🍖", category: "Shashlik", popular: true, time: "35 daq", desc: "Qo'y go'shtidan tayyor shashlik" },
    { id: 602, name: "Mol shashlik (6 ta)", price: 68000, emoji: "🥩", category: "Shashlik", popular: true, time: "35 daq", desc: "Mol go'shtidan marinadi shashlik" },
    { id: 603, name: "Tovuq shashlik (6 ta)", price: 55000, emoji: "🍗", category: "Shashlik", popular: false, time: "30 daq", desc: "Tovuq filesi, asal-limon marinadi" },
    { id: 604, name: "Qovurma lag'mon", price: 42000, emoji: "🍜", category: "Asosiy", popular: true, time: "25 daq", desc: "Go'sht va sabzavot bilan qovurilgan lag'mon" },
    { id: 605, name: "Achiq-chuchuk salat", price: 22000, emoji: "🥗", category: "Salat", popular: false, time: "10 daq", desc: "Yangi sabzavotlar, o'tkir sous" },
  ],
  7: [
    { id: 701, name: "Original Bucket (8 ta)", price: 95000, emoji: "🍗", category: "Tovuq", popular: true, time: "20 daq", desc: "8 ta qovurilgan tovuq bo'lagi" },
    { id: 702, name: "Zinger Burger", price: 42000, emoji: "🍔", category: "Burger", popular: true, time: "18 daq", desc: "Qovurilgan tovuq, kabob sousi, salat" },
    { id: 703, name: "Popcorn Chicken", price: 32000, emoji: "🍿", category: "Snack", popular: true, time: "15 daq", desc: "Mini tovuq bo'laklari, tatli-achchiq sous" },
    { id: 704, name: "Katta Kartoshka + Kola", price: 25000, emoji: "🍟", category: "Set", popular: false, time: "10 daq", desc: "Katta kartoshka va 0.5L kola" },
  ],
  8: [
    { id: 801, name: "Samarqand oshi (1 kg)", price: 50000, emoji: "🫕", category: "Asosiy", popular: true, time: "30 daq", desc: "Samarqand uslubida pishirilgan osh" },
    { id: 802, name: "Dimlama (porsiya)", price: 45000, emoji: "🥘", category: "Asosiy", popular: true, time: "35 daq", desc: "Ko'p sabzavotli an'anaviy dimlama" },
    { id: 803, name: "Somsa (3 ta)", price: 22000, emoji: "🥟", category: "Non-Somsa", popular: false, time: "15 daq", desc: "Katta tandirda pishirilgan go'shtli somsa" },
    { id: 804, name: "Obi non", price: 10000, emoji: "🫓", category: "Non-Somsa", popular: false, time: "10 daq", desc: "Samarqand non: yupqa va xushbo'y" },
    { id: 805, name: "Ko'k choy (1 choynak)", price: 14000, emoji: "🍵", category: "Ichimlik", popular: true, time: "5 daq", desc: "Samarqandning yashil choyi" },
  ]
}

export const formatPrice = (p) => p.toLocaleString('uz-UZ') + ' so\'m'

export const STATUS_MAP = {
  pending: { label: 'Kutilmoqda', color: 'orange', emoji: '⏳' },
  confirmed: { label: 'Qabul qilindi', color: 'blue', emoji: '✅' },
  preparing: { label: 'Tayyorlanmoqda', color: 'orange', emoji: '👨‍🍳' },
  on_way: { label: "Yo'lda", color: 'blue', emoji: '🛵' },
  delivered: { label: 'Yetkazildi', color: 'green', emoji: '🎉' },
  cancelled: { label: 'Bekor qilindi', color: 'red', emoji: '❌' },
}
